# Make file for tmvp (text mode video player)
#   Copyright (c) 2006 by Da Fox && Hackykid.
#       make -B                 Will build aavp.exe
#       make -B -DDEBUG         Will build the debug version of aavp.exe
NAME=tmvp
!if $d(DEBUG)
TASMDEBUG=/zi
LINKDEBUG=/v
!else
TASMDEBUG=
LINKDEBUG=
!endif

!if $d(MAKEDIR)
THEINCLUDE=-I$(MAKEDIR)\..\include
!else
THEINCLUDE=
!endif

DEF  = $(NAME).def

#TASM_OPTIONS = $(TASMDEBUG) /dMDL=flat /m $(THEINCLUDE)
TASM_OPTIONS = $(TASMDEBUG) /m $(THEINCLUDE)

wdosx : $(NAME).exe
  stubit $(NAME).exe
   
$(NAME).exe : $(NAME).obj init.obj smallfnc.obj vsprintf.obj printf.obj prscmdln.obj fopen.obj
  tlink32 /Tpe /c $(LINKDEBUG) $(NAME)+init+smallfnc+vsprintf+printf+prscmdln+fopen,$(NAME),,, $(DEF)

.ASM.OBJ :
  tasm32 /p /t /w+ /z $(TASM_OPTIONS) $*

tmvp.obj     : $(NAME).asm globals.inc
init.obj     : init.asm globals.inc
smallfnc.obj : smallfnc.asm globals.inc
printf.obj   : printf.asm globals.inc
vsprintf.obj : vsprintf.asm globals.inc
prscmdln.obj : prscmdln.asm globals.inc
fopen.obj    : fopen.asm globals.inc
